version: '3.8'
services:
  db:
    image: clue/json-server
    ports:
      - 80:80
    volumes:
      - ./src/persistence:/data
  app:
    image: node
    ports:
      - 3000:3000
    command: "npm start ./src/index.js"
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app

